# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mapping <- function(cov_est, theta_0, update_w, update_change, regularizer, max_iter, tol) {
    .Call('changepoints_mapping', PACKAGE = 'changepoints', cov_est, theta_0, update_w, update_change, regularizer, max_iter, tol)
}

log_likelihood <- function(data, theta0, theta1, tau, regularizer) {
    .Call('changepoints_log_likelihood', PACKAGE = 'changepoints', data, theta0, theta1, tau, regularizer)
}

proposal_uniform <- function(N, buff) {
    .Call('changepoints_proposal_uniform', PACKAGE = 'changepoints', N, buff)
}

proposal_gaussian <- function(tau, N, buff, sigma2) {
    .Call('changepoints_proposal_gaussian', PACKAGE = 'changepoints', tau, N, buff, sigma2)
}

proposal_mixture <- function(tau, N, buff, sigma2, beta) {
    .Call('changepoints_proposal_mixture', PACKAGE = 'changepoints', tau, N, buff, sigma2, beta)
}

simulated_annealing <- function(data, tau = -1L, buff = 10L, regularizer = 1., update_w = 1., update_change = 0.9, mapping_iter = 1L, max_iter = 500L, cooling = 0L, kernel = 0L, beta_min = 0.01, d = 1.1, tol = 0.00001) {
    .Call('changepoints_simulated_annealing', PACKAGE = 'changepoints', data, tau, buff, regularizer, update_w, update_change, mapping_iter, max_iter, cooling, kernel, beta_min, d, tol)
}

