# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mapping <- function(cov_est, theta_start, update_w, update_change, regularizer, max_iter, tol) {
    .Call('changepoints_mapping', PACKAGE = 'changepoints', cov_est, theta_start, update_w, update_change, regularizer, max_iter, tol)
}

gg_log_likelihood <- function(data, theta_i, regularizer) {
    .Call('changepoints_gg_log_likelihood', PACKAGE = 'changepoints', data, theta_i, regularizer)
}

